import Head from "next/head";
import { Inter } from "next/font/google";
import createApolloClient from "@/util/apollo-client";
import { gql } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

type PropType = { countries: Array<any> };

export default function Home({ countries }: PropType) {
  return (
    <>
      <Head>
        <title>Leonardo.AI Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {countries.map((country) => (
            <div key={country.code}>
              <h3>
                {country.name} ({country.code})
              </h3>
              <div>
                Captial: {country.capital}, Language:{" "}
                {country.languages[0]?.name}
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const client = createApolloClient();

  const { data } = await client.query({
    query: gql`
      query Countries {
        countries(filter: { currency: { eq: "USD" } }) {
          code
          name
          capital
          languages {
            name
          }
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries,
    },
  };
}
