import Head from "next/head";
import { Inter } from "next/font/google";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { getSession } from "next-auth/react";
import { UserContext } from "@/context/UserContext";
import Home from "@/components/Home/Home";

const inter = Inter({ subsets: ["latin"] });

export default function Root() {
  const [isLoading, setIsLoading] = useState(true);
  const router = useRouter();

  const { user, setUser, hasProfile } =
    useContext<UserContextType>(UserContext);

  useEffect(() => {
    getSession().then((session) => {
      if (!session) {
        router.replace("/login");
      } else {
        setIsLoading(false);
        setUser(session as unknown as User);
      }
    });
  }, [router, setUser]);

  if (isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <>
      <Head>
        <title>Leonardo.AI Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
}
